version: '2'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  influxdb:
    image: tutum/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - PRE_CREATE_DB=svante
